name: Create Release on Tag

on:
  push:
    tags:
      - "v*.*.*"   # löst z. B. bei v1.2.3 aus
  workflow_dispatch:  # manueller Start möglich

permissions:
  contents: write     # nötig, um Releases zu erstellen

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # zeigt der Action die Historie für Notes

      # Optional: Mini-Changelog aus Git-Logs für den Zeitraum seit letztem Tag
      - name: Build tag-scoped changelog (optional)
        id: changelog
        run: |
          CURR_TAG="${GITHUB_REF#refs/tags/}"
          PREV_TAG="$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || true)"
          {
            if [ -n "$PREV_TAG" ]; then
              echo "## Changes since $PREV_TAG"
              git log --pretty=format:'- %s (%h)' "$PREV_TAG..$CURR_TAG"
            else
              echo "## Changes in $CURR_TAG"
              git log --pretty=format:'- %s (%h)'
            fi
          } > CHANGELOG_TAG.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true   # nutzt GitHub’s Auto-Notes (PRs, Commits)
          append_body: true              # hängt optionalen Changelog unten an
          body_path: CHANGELOG_TAG.md    # kannst du auch entfernen, wenn nicht gewünscht
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}