name: Update README structure

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

# Verhindert Endlosschleifen, wenn der Bot selbst committet
permissions:
  contents: write

jobs:
  update-structure:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Falls dein Script zusätzliche Pakete braucht, hier installieren:
      # - name: Install deps
      #   run: pip install -r requirements.txt

      - name: Generate structure section
        run: |
          python generate_structure_with_images.py

      - name: Commit changes (if any)
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: update README structure"
            git push
          fi